services:
  mongodb:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27107"
    environment:
      MONGO_USER: ${MONGO_ADM_USER:changeme}
      MONGO_PASSWD: ${MONGO_ADM_PASSWD:changeme}
    volumes:
      - mongo_data:/data/db

backend:
  build: /backend
  container_name: backend
  ports:
    - "7777:7777"
  environment:
    MONGO_URI: ${ADM_MONGO_URI}
  volumes: 
    - .:/app
  depends_on:
    - mongodb
  