[project]
name="Conteneurisation-Orchestration"
version="0.0.0"
authors=[
    {name = "AGOSTINO Romeo"}, 
    {name = "BIGAND Theo"}, 
    {name = "DRAME Moussa"}, 
    {name = "AUDIBERT Mathieu"}
]
readme="README.md"
requires-python=">=3.10"